version: '3.7'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    environment:
      MYSQL_ROOT_PASSWORD: asdb
    volumes:
      - db:/var/lib/mysql
    ports: 
      - 3306:3306

volumes:
  db: